### ISSUE TITLE
Ignored unknown options appearing at top of file

### ISSUE THREAD

**Issue by ajcrites** [prettier/vim-prettier#100]
This just came up recently, so I'm really not sure what could be the root cause. I have been using the same prettier configuration. I'm installing this plugin through dein:

    let g:prettier#autoformat = 0

    let g:prettier#config#parser = 'typescript'
    let g:prettier#config#single_quote = 'true'
    let g:prettier#config#trailing_comma = 'all'
    let g:prettier#config#bracket_spacing = 'true'

    autocmd BufWritePre *.ts PrettierAsync

Whenever I save a `.ts` file or run `:PrettierAsync`, my files are immediately prepended with

    Ignored unknown option: --prose-wrap

    Ignored unknown option: --no-editorconfig

    Ignored unknown option: --loglevel

In order to get around this issue I've tried restoring and removing my global installation of `prettier`. It doesn't seem to matter, and I always get this text prepended to my file when I try running `vim-prettier`.

**Comment by mitermayer** [comment]
Hi @ajcrites,

Could you please confirm that:

1. Vim prettier version is up to date 0.2.6 by checking output of: 

```
:PrettierVersion
```

2. Check that you are really using a prettier CLI with version over 1.9 by checking output of:

```
:PrettierCliVersion
```

3. If the above version is not what you expected you can check what is the resolved prettier cli by checking output of:

```
:PrettierCliPath
```

*** 

Sometimes you may have the global installed prettier version of 1.9+ but you may be working on projects that still have the old prettier installed on their `package.json` and available on their `node_modules` in that case `vim-prettier` will resolve that `prettier` version instead of your global one

**Comment by mitermayer** [comment]
Feel free to comment or re-open this issue if that does not fix your use-case, I have closed this issue since that is a common issue faced by other users. I will update the README with a FAQ area that explains this use case

**Comment by sloansparger** [comment]
I just ran into this issue as well. This was printed out at the top of my file:
```
Ignored unknown option: --arrow-parens

Ignored unknown option: --prose-wrap

Ignored unknown option: --no-editorconfig

Ignored unknown option: --loglevel
```
`:PrettierVersion` returns `0.2.6`
`:PrettierCliVersion` returns `1.7.4`
`:PrettierCliPath` returns `/Users/Sloan/<redacted>/<my-project-folder>/node_modules/.bin/prettier

However, I haven't noticed this happening on another project were the prettier cli version `1.10.2` so upgrading versions might be useful to others facing this issue. However, to help debug why this might have happened here are my overrides in my `.vimrc` also:
```
let g:prettier#quickfix_enabled = 0
let g:prettier#autoformat = 0
autocmd BufWritePre *.js,*.jsx,*.mjs,*.ts,*.tsx,*.css,*.less,*.scss,*.json,*.graphql,*.md,*.vue PrettierAsync
let g:prettier#config#print_width = 100
let g:prettier#config#semi = 'false'
let g:prettier#config#single_quote = 'true'
let g:prettier#config#bracket_spacing = 'true'
let g:prettier#config#trailing_comma = 'es5'
```

**Comment by jsatk** [comment]
I'm also seeing the above issue @sloansparger mentioned. I'm on Prettier 0.2.6.

**Comment by mitermayer** [comment]
Hi @sloansparger,

The reason why you are seing that on top of your file is due to using an old `prettier` version, notice that you are using the latest `vim-prettier` with a `prettier` cli of version `1.7.4`.

If you really need to use older prettier versions, I suggest you pinning your `vim-prettier` to older released versions that are supporting that particular version.

@jsatk , could you also check your `prettier` resolved CLI veersion to see if your problem is the same as the above ? You can do so by typing `:PrettierCliVersion` within vim, also could you check your resolved `prettier` path by `:PretttierCliPath` to ensure that you are using the resolved prettier you intended in the first place ?

If the above does not solve your issues please let me know and I am more than happy to try debug it for you

**Comment by jsatk** [comment]
@mitermayer I'm on CLI version 1.5.2. Pinning my vim-prettier version to tag 0.0.11 got it working for me. Thanks for the response!

Bummed the latest isn't flexible enough to work with older versions, but I get it. Happy to help contribute when I can if you need any extra contributors.

**Comment by jsatk** [comment]
Thanks so much @mitermayer

**Comment by somtodev** [comment]
Thanks @mitermayer

I had to install the latest vim-prettier version from vimawesome

then, I installed Prettier(v2.3.0)

Gladly said bye to those outputs at the top.

**Comment by trabeast** [comment]
> Thanks @mitermayer
> 
> I had to install the latest vim-prettier version from vimawesome
> 
> then, I installed Prettier(v2.3.0)
> 
> Gladly said bye to those outputs at the top.

This worked for me!
