### ISSUE TITLE
Trailing comma is causing issues with IE10/11

### ISSUE THREAD

**Issue by CaioBianchi** [prettier/vim-prettier#45]
The default setting:

```
" none|es5|all
g:prettier#config#trailing_comma = 'all'
```

is causing IE 10 and 11 to trigger an error on JS files.
Perhaps this settings should be set to "none" by default?

**Comment by mitermayer** [comment]
Hi @CaioBianchi,

Thank you for raising that, the defaults on vim-prettier are based on the [Facebook Prettier Options](https://github.com/prettier/eslint-plugin-prettier/blob/6de494fd685a107f3a9a371e663a1f8d68d6d31f/README.md#options)

Once the next [prettier](https://github.com/prettier/prettier) version is released it will include support for [custom configurations](prettier/prettier#2589) since that functionality was integrated on prettier/prettier#2434.

Once that is also integrated back in `vim-prettier` it should be a lot easier to change those settings per project basis.

***

In the meantime you can set the default to none on your `$HOME/.vimrc`

```vim
g:prettier#config#trailing_comma = 'none'
```

**Comment by CaioBianchi** [comment]
Thanks @mitermayer. I did that. I was just wondering if that was something unintentional.
