### ISSUE TITLE
:Prettier make cursor history wrong when navigating with <C-O>

### ISSUE THREAD

**Issue by trungdq88** [prettier/vim-prettier#48]
After I run `:Prettier`, and then press `<C-o>` to navigate to the last position of cursor, it always point to the beginning of the file. It's annoying. Please fix this.

**Comment by mitermayer** [comment]
Hi @trungdq88 thanks for reporting this issue. 

Will investigate this soon, otherwise feel free to submit a PR.

**Comment by trungdq88** [comment]
I wish I could, but I have no knowledge of vim script :(

**Comment by mitermayer** [comment]
I tested this issue with other similar formatting plugins and they all have similar problems. :( In the meantime will merge a PR that will at least mitigate this issue. 

You will still have to do the <C-O> 2 times but the first time it wont take you to the top of the file (as the current described behavior) it will instead keep you on the same place.

**Comment by mitermayer** [comment]
@trungdq88 closed this issue since at this stage I am not sure that I can edit vim jump history to delete the duplicate same line entry.  

I did however merge a PR that at least makes sure that when doing a <C-O> you do not jump to the beginning of the file anymore

**Comment by trungdq88** [comment]
That's good enough for me 👍  Thanks a lot!

**Comment by mortyccp** [comment]
FYI: [vim-go](https://github.com/fatih/vim-go) has format but it keeps the cursor position and history. You might take a look on how it achieves that.

**Comment by mitermayer** [comment]
@mortyccp  great finding!

managed to find where they achieve that:

https://github.com/fatih/vim-go/blob/86834ce79a00325d15a27f74733980d98ef06ad7/autoload/go/asmfmt.vim#L40 

and on 

https://github.com/fatih/vim-go/blob/5730b71ea57c3db0972968889a1d098139cb6031/autoload/go/fmt.vim#L53

Are examples of them deleting history, if you want to send a PR to `vim-prettier` you just need to adapt that similar logic to: https://github.com/prettier/vim-prettier/blob/master/autoload/prettier.vim#L176

Otherwise will see if I can squeeze sometime in to do that over the weekend

**Comment by mortyccp** [comment]
@mitermayer Sorry, I am not familiar with VimL
