### ISSUE TITLE
Question. Why differ from prettier?

### ISSUE THREAD

**Issue by dchang-dchang** [prettier/vim-prettier#58]
HI! Thanks so much for all your work on `prettier` and `vim-prettier`. It was exactly what I was looking for after having used `gofmt`.

I'm super curious - on the [readme](https://github.com/prettier/vim-prettier/blob/master/README.md#overwrite-default-prettier-configuration), you say that you differ from Prettier intentionally. Would love to better understand the reasoning as I'm currently trying to configure it to act the same as Prettier. Thanks!

**Comment by mitermayer** [comment]
Hi @dchang-dchang,

Thank you for your kind words. The reason why we differ from prettier is because we are also used internally at Facebook and we follow the Facebook prettier configuration format (https://github.com/prettier/eslint-plugin-prettier#options). 

You can update the default `vim-prettier` settings to better suit your company/project by either updating your `.vimrc` configuration or by even creating a `~/.prettierrc` on your home directory or adding custom project configurations on the format supported by the `prettier` cli on your project.

Feel free to comment in this issue if you have any further questions around it.

**Comment by dchang-dchang** [comment]
@mitermayer Thanks for the quick reply! That makes a lot of sense - was noticing that vim-prettier matched react's prettier flags.

Mind if I ask a newbie question? How do you manage differing prettier configurations across projects?

Let's say I want to contribute to Yarn and also React and they have different prettier settings. Do you manually edit `.vimrc` every time you change between these project folders? Or do you just keep vim-prettier one way and then rely on pre-commit hooks that run the project's prettier to undo what vim-prettier changed?

**Comment by dchang-dchang** [comment]
No need to respond. Found the answer to my own question. Did not know that vi had project specific settings!

http://vim.wikia.com/wiki/Project_specific_settings

**Comment by helixbass** [comment]
@dchang-dchang looks like `vim-prettier` respects project-specific `.prettierrc` (at least in the current directory), even overriding options set via `let g:prettier#config#[...]` in `~/.vimrc`. So you don't have to go to the trouble of using vim's own project-specific settings mechanism

**Comment by masaeedu** [comment]
Hi @mitermayer. I tried using a `.prettierrc` file in my home directory as you mentioned but it doesn't seem to be picked up. If I move it next to the JS file it works as expected. Does this feature depend on all the user's code being under the home directory perhaps?

**Comment by mitermayer** [comment]
Hi @masaeeudu,

The code used to find where configuration files exists are from prettier itself not from vim-prettier, it should work.

If you try to run prettier from the command line on the same directory does that work for you ?

The prettier resolution path to find configuration files is to look recursively among parents until finding the config. Is there a chance that you may be editing a file in a directory not inside your home directory?
