### ISSUE TITLE
Confused by file type overrides

### ISSUE THREAD

**Issue by michaeljones** [prettier/vim-prettier#60]
Thanks for writing the plugin. Keen to start using it but I've just had a very confusing 30 mins whilst I tried to figure out why vim-prettier seemed to be ignoring my prettier project config file.

I feel that the README indicates that prettier defaults to 'prefer-file'. But in order to get that behaviour when using typescript I have to delete these lines: 

https://github.com/prettier/vim-prettier/blob/3cde181b6b5481496b21bd35b832bdee25df267d/ftplugin/typescript.vim#L1-L4

Though I've used vim for a long time, I'm one of those that has never really learnt even the basics of vim script so I'm not sure how to override that setting myself.

Hope this is a reasonable concern to raise. I'm sure I could work around it if I knew more about vim but it seems confusing behaviour to start with. Maybe I'm missing something basic. It wouldn't be the first time I've missed something in the docs.

Thanks for the project though :)

**Comment by mitermayer** [comment]
Hi @michaeljones,

Thank you for this message, the reason why I had to manually add `cli-override` was due to this issue https://github.com/prettier/prettier/issues/2946, but now that  I just noticed prettier release `1.7.4` I should be able to properly fix this in vim-prettier.

I will be working on this issue now and do a release for it soon, once release it should just work with your project file without needing any configuration

**Comment by mitermayer** [comment]
Hi @michaeljones,

I have just done a release with this fix, please upgrade your `vim-prettier` plugin. It should work now as you expected assuming the project you work on is using prettier 1.7.4+

**Comment by michaeljones** [comment]
Wow, thanks for such a quick resolution @mitermayer! Updating now :D
