### ISSUE TITLE
Incorrect resolving of prettier config

### ISSUE THREAD

**Issue by sunflowerdeath** [prettier/vim-prettier#71]
Prettier uses following logic for resolving config:

> The configuration file will be resolved starting from the location of the file being formatted, and searching up the file tree until a config file is (or isn't) found.

Plugin should resolve config of each file using command `prettier --find-config-path ./my/file.js`

This causes issues when I use following project structure:
```
|- node_modules/
|  |- prettier/
|- packageA/
|  |- src/
|  |  |- index.js
|  |- prettier.config.js
|- packageB/
|  |- src/
|  |  |- index.js
|  |- prettier.config.js
```
 Plugin doesn't use configs from corresponding directories and formats both files `packageA/src/index.js` and `packageB/src/index.js` with default config.

**Comment by mitermayer** [comment]
Hi @sunflowerdeath 

Thanks for reporting this issue, will try to look into it during the weekend, otherwise feel free to open a PR.

If you want to contribute I think this could be achieved by editing the CLI arguments passed to the prettier CLI on https://github.com/prettier/vim-prettier/blob/master/autoload/prettier.vim#L238 and include the following:

```viml
          \ ' --find-config-path  ' .
          \ simplify(expand("%:t"))  .
```

Otherwise I will look into it during the weekend

**Comment by mitermayer** [comment]
@sunflowerdeath Thanks for reporting this! Fixed this via https://github.com/prettier/vim-prettier/pull/72 and just did a new release 0.2.4 with this fix!
