### ISSUE TITLE
prepends `Ignored unknown option: --config-precedence` in buffer

### ISSUE THREAD

**Issue by jojoyuji** [prettier/vim-prettier#73]
When executing `:Prettier` it prepends `Ignored unknown option: --config-precedence` in buffer

I'm using `vim-prettier 0.2.4`
with `global prettier version 1.7.4`

I believe it's related to https://github.com/prettier/vim-prettier/issues/53

**Comment by mitermayer** [comment]
Hi @jojoyuji 

Could you please confirm that:

1. Vim prettier version is 0.2.4 by checking output of: 

```
:PrettierVersion
```

2. Check that you are really using a prettier CLI with version over 1.7.4 by checking output of:

```
:PrettierCliVersion
```

3. If the above version is not what you expected you can check what is the resolved prettier cli by checking output of:

```
:PrettierCliPath
```

*** 

Sometimes you may have the global installed prettier version of 1.7.4+ but you may be working on projects that still have the old prettier installed on their `package.json` and available on their `node_modules` in that case `vim-prettier` will resolve that `prettier` version instead of your global one

**Comment by jojoyuji** [comment]
Woah, found the issue! 

I had updated my prettier globaly indeed, however I realized that `vim-prettier` was using my current project's Prettier by running the `:PrettierCliPath` 

Thx @mitermayer for the help.

**Comment by jojoyuji** [comment]
> Sometimes you may have the global installed prettier version of 1.7.4+ but you may be working on projects that still have the old prettier installed on their package.json and available on their  node_modules in that case vim-prettier will resolve that prettier version instead of your global one

hey @mitermayer just wondering here:

 isn't 
``` 
let g:prettier#exec_cmd_path = "~/path/to/cli/prettier"
```

supposed to override even a local project prettier? 

I mean, since you're pretty much setting the path for the bin file itself, it just doesn't feel right...

What you think?
