### ISSUE TITLE
Deletes file contents of files ignored by .prettierignore

### ISSUE THREAD

**Issue by blacksails** [prettier/vim-prettier#92]
When I save a file ignored by a .prettierignore file, then its contents is deleted.

**Comment by mitermayer** [comment]
Hi @blacksails,

Thanks fro reporting this, will investigate this soon and if is caused by vim-prettier will fix asap and do a new release. Otherwise will comment in here my findings.

**Comment by mitermayer** [comment]
@blacksails 

The problem in here is due to `prettier` itself not giving any `stdout` when ignoring the file parsing. `vim-prettier` has no way to know that the file has not being parsed since it cannot read `.prettierinore` files on its own.

@lydell  @azz , would be great if files that are ignored by `.prettierignore` could be simply printed as it is without formatting, maybe some extra CLI params to make that happen ?

**Comment by mitermayer** [comment]
Will raise this issue in prettier itself

**Comment by mitermayer** [comment]
raised https://github.com/prettier/prettier/issues/3590

**Comment by mitermayer** [comment]
In the meantime will do a workaround on `vim-prettier` itself for this by not replacing editing contents with empty stdout
